# Default values for wreditor

remote_dcp: true



storage:
  access_key: "<S3 Access Key>"
  secret_key: "<S3 Secret Key>"
  # api_endpoint can be blank if using AWS S3, otherwise, set to your providers S3 endpoint
  api_endpoint: ""

  # s3:// url to S3 storage, eg. s3://my-bucket/perma-fact/dev/
  storage_prefix: "<s3://my-bucket/perma-fact/dev/"

  # https:// url, publicly access prefix for the s3 storage (for preview):
  access_prefix: "<https://my-bucket.s3.amazonaws.com/perma-fact/dev/>"

  # acl settings, if any
  # to enable uploaded files to be public, set to:
  # acl: "public-read"
  acl: ""

# duration of storage artifacts left in block storage
job_cleanup_interval: "240"

# max duration of each job, if not finished by this time, will be stopped and considered failed
job_max_duration: "10"

# num replicas for api backend
num_backend_replicas: "2"

# application
name: browserkube

# docker image tag version
version: latest

# optional: if 'host' is set, a publicly accessible Ingress controller is created with an SSL cert (using letsencrypt)
ingress:
  host: ""
  cert_email: "my-email-for-letsencrypt@example.com"

# optional: uncomment annotations to add one or more 'name: value' mappings to the service,
# e.g.
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
# uncomment type to match, if necessary
#service:
#  annotations:
#    name: value
#  type: LoadBalancer

# Advanced options
browser:
  image: chrome:84

# enable VNC for direct browser API
vnc: False

# idle timeout for reconnection when using VNC
idle_timeout: 60

# headless: must be False if using VNC
headless: True

# path to browser profile to use
profile_url: ""

# endpoint to load profile from
profile_api_endpoint: ""


